print("I can write sentences here")
print("helloworld".upper())
print("hello world".upper()
print("     1   1     ")  
print("     1   1     ")
print("     1   1     ")
print("_ _ _ _ _ _ _ _ _ _ _ ")
print("     1    1    ")
print("     1    1    ")
print("     1    1    ")
print("_ _ _ _ _ _ _ _ _ _ _ ")
print("     1    1    ")
print("     1    1    ")
print("     1    1    ")
